# Generated by Django 4.2 on 2025-11-05 14:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga_barang', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
            },
        ),
        migrations.CreateModel(
            name='Faktur',
            fields=[
                ('id_faktur', models.AutoField(primary_key=True, serialize=False)),
                ('total_faktur', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='diproses', max_length=20)),
                ('berat', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('koli', models.IntegerField(default=0)),
                ('foto_pengiriman', models.ImageField(blank=True, null=True, upload_to='faktur_images/')),
            ],
            options={
                'verbose_name': 'Faktur',
                'verbose_name_plural': 'Faktur',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id_kecamatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kecamatan', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id_kelurahan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelurahan', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan',
                'verbose_name_plural': 'Kelurahan',
            },
        ),
        migrations.CreateModel(
            name='Kurir',
            fields=[
                ('id_kurir', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=10)),
                ('no_hp', models.CharField(blank=True, max_length=20, null=True)),
                ('alamat', models.TextField(blank=True, null=True)),
                ('aktif', models.BooleanField(default=True)),
                ('tanggal_bergabung', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Kurir',
                'verbose_name_plural': 'Kurir',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id_vendor', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id_pembeli', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelurahan')),
            ],
            options={
                'verbose_name': 'Pembeli',
                'verbose_name_plural': 'Pembeli',
            },
        ),
        migrations.CreateModel(
            name='Keluhan',
            fields=[
                ('id_keluhan', models.AutoField(primary_key=True, serialize=False)),
                ('isi_keluhan', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='keluhan_images/')),
                ('tanggal', models.DateTimeField(default=django.utils.timezone.now)),
                ('faktur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.faktur')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pembeli')),
            ],
            options={
                'verbose_name': 'Keluhan',
                'verbose_name_plural': 'Keluhan',
            },
        ),
        migrations.AddField(
            model_name='faktur',
            name='kurir',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='faktur', to='core.kurir'),
        ),
        migrations.AddField(
            model_name='faktur',
            name='pembeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktur', to='core.pembeli'),
        ),
        migrations.AddField(
            model_name='faktur',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktur', to='core.vendor'),
        ),
        migrations.CreateModel(
            name='DetailFaktur',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_barang', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.barang')),
                ('faktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.faktur')),
            ],
            options={
                'verbose_name': 'Detail Faktur',
                'verbose_name_plural': 'Detail Faktur',
            },
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori'),
        ),
    ]
