# Generated by Django 5.2.7 on 2025-10-12 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga_barang', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Faktur',
            fields=[
                ('id_faktur', models.AutoField(primary_key=True, serialize=False)),
                ('total_faktur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='diproses', max_length=20)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('koli', models.IntegerField()),
                ('foto_pengiriman', models.ImageField(upload_to='faktur_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id_kecamatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kecamatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Kurir',
            fields=[
                ('id_kurir', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kurir', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id_vendor', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DetailFaktur',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_barang', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.barang')),
                ('faktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.faktur')),
            ],
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori'),
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id_kelurahan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelurahan', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kecamatan')),
            ],
        ),
        migrations.AddField(
            model_name='faktur',
            name='kurir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kurir'),
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id_pembeli', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelurahan')),
            ],
        ),
        migrations.CreateModel(
            name='Keluhan',
            fields=[
                ('id_keluhan', models.AutoField(primary_key=True, serialize=False)),
                ('isi_keluhan', models.TextField()),
                ('foto_keluhan', models.ImageField(blank=True, null=True, upload_to='keluhan_images/')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pembeli')),
            ],
        ),
        migrations.AddField(
            model_name='faktur',
            name='pembeli',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktur', to='core.pembeli'),
        ),
        migrations.AddField(
            model_name='faktur',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktur', to='core.vendor'),
        ),
    ]
