# Generated by Django 4.2 on 2025-10-26 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barang',
            fields=[
                ('id_barang', models.AutoField(primary_key=True, serialize=False)),
                ('nama_barang', models.CharField(max_length=100)),
                ('harga_barang', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Barang',
                'verbose_name_plural': 'Barang',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id_kategori', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
            },
        ),
        migrations.CreateModel(
            name='Kecamatan',
            fields=[
                ('id_kecamatan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kecamatan', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Kecamatan',
                'verbose_name_plural': 'Kecamatan',
            },
        ),
        migrations.CreateModel(
            name='Kelurahan',
            fields=[
                ('id_kelurahan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kelurahan', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('kecamatan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kecamatan')),
            ],
            options={
                'verbose_name': 'Kelurahan',
                'verbose_name_plural': 'Kelurahan',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id_vendor', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='Pembeli',
            fields=[
                ('id_pembeli', models.AutoField(primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=100)),
                ('alamat', models.TextField()),
                ('no_hp', models.CharField(max_length=20)),
                ('kelurahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kelurahan')),
            ],
            options={
                'verbose_name': 'Pembeli',
                'verbose_name_plural': 'Pembeli',
            },
        ),
        migrations.CreateModel(
            name='Keluhan',
            fields=[
                ('id_keluhan', models.AutoField(primary_key=True, serialize=False)),
                ('isi_keluhan', models.TextField()),
                ('foto_keluhan', models.ImageField(blank=True, null=True, upload_to='keluhan_images/')),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pembeli')),
            ],
            options={
                'verbose_name': 'Keluhan',
                'verbose_name_plural': 'Keluhan',
            },
        ),
        migrations.CreateModel(
            name='Faktur',
            fields=[
                ('id_faktur', models.AutoField(primary_key=True, serialize=False)),
                ('total_faktur', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('diproses', 'Diproses'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='diproses', max_length=20)),
                ('berat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('koli', models.IntegerField()),
                ('foto_pengiriman', models.ImageField(upload_to='faktur_images/')),
                ('kurir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktur_kurir', to=settings.AUTH_USER_MODEL)),
                ('pembeli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktur', to='core.pembeli')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faktur', to='core.vendor')),
            ],
            options={
                'verbose_name': 'Faktur',
                'verbose_name_plural': 'Faktur',
            },
        ),
        migrations.CreateModel(
            name='DetailFaktur',
            fields=[
                ('id_detail', models.AutoField(primary_key=True, serialize=False)),
                ('jumlah_barang', models.IntegerField()),
                ('barang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.barang')),
                ('faktur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='core.faktur')),
            ],
            options={
                'verbose_name': 'Detail Faktur',
                'verbose_name_plural': 'Detail Faktur',
            },
        ),
        migrations.AddField(
            model_name='barang',
            name='kategori',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kategori'),
        ),
    ]
