# Generated by Django 4.2 on 2025-10-17 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barang',
            options={'verbose_name': 'Barang', 'verbose_name_plural': 'Barang'},
        ),
        migrations.AlterModelOptions(
            name='detailfaktur',
            options={'verbose_name': 'Detail Faktur', 'verbose_name_plural': 'Detail Faktur'},
        ),
        migrations.AlterModelOptions(
            name='faktur',
            options={'verbose_name': 'Faktur', 'verbose_name_plural': 'Faktur'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategori'},
        ),
        migrations.AlterModelOptions(
            name='kecamatan',
            options={'verbose_name': 'Kecamatan', 'verbose_name_plural': 'Kecamatan'},
        ),
        migrations.AlterModelOptions(
            name='keluhan',
            options={'verbose_name': 'Keluhan', 'verbose_name_plural': 'Keluhan'},
        ),
        migrations.AlterModelOptions(
            name='kelurahan',
            options={'verbose_name': 'Kelurahan', 'verbose_name_plural': 'Kelurahan'},
        ),
        migrations.AlterModelOptions(
            name='kurir',
            options={'verbose_name': 'Kurir', 'verbose_name_plural': 'Kurir'},
        ),
        migrations.AlterModelOptions(
            name='pembeli',
            options={'verbose_name': 'Pembeli', 'verbose_name_plural': 'Pembeli'},
        ),
        migrations.AlterModelOptions(
            name='vendor',
            options={'verbose_name': 'Vendor', 'verbose_name_plural': 'Vendor'},
        ),
    ]
