# Generated by Django 4.2 on 2025-10-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktur',
            name='berat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='faktur',
            name='foto_pengiriman',
            field=models.ImageField(blank=True, null=True, upload_to='faktur_images/'),
        ),
        migrations.AlterField(
            model_name='faktur',
            name='koli',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='faktur',
            name='total_faktur',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
