# Generated by Django 4.2 on 2025-11-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_keluhan_faktur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
